### ISSUE TITLE
What does your phone homescreen look like?

### ISSUE THREAD

**Issue by sindresorhus** [DIYgod/ama#1]
Screenshot please. I ask everyone this as it tells a lot about a person. [Mine for example.](https://github.com/sindresorhus/ama/issues/64)

**Comment by DIYgod** [comment]
![Screenshot](http://7bv8xp.com5.z0.glb.clouddn.com/Screenshot_2015-07-12-10-25-14.png)

**Comment by zinking** [comment]
@sindresorhus you are absolutely correct.
